name: Pipeline

on:
  push:
    branches:
      - prerelease

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull prerelease into TEST and run
        shell: powershell
        run: |
          cd "C:\Users\miks1\Documents\STUNDAS DARBS\TEST\stundas_darbs"
          git switch prerelease
          git pull origin prerelease
          python hello_world.py

      - name: Merge prerelease into main
        shell: powershell
        run: |
          cd "C:\Users\miks1\Documents\STUNDAS DARBS\MAIN\stundas_darbs"

          git fetch origin
          git switch main
          git pull origin main

          git merge origin/prerelease

          python hello_world.py