name: Main to Prerelease Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-prerelease:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        shell: powershell
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      # MAIN -> PRERELEASE
      - name: Update prerelease branch
        shell: powershell
        run: |
          git fetch origin

          git switch -C prerelease origin/prerelease

          git merge origin/main --no-edit

          git push origin prerelease

      # UPDATE TEST FOLDER FROM PRERELEASE
      - name: Update TEST folder
        shell: powershell
        run: |
          cd "C:\Users\miks1\Documents\STUNDAS DARBS\TEST\stundas_darbs"

          git fetch origin

          git switch -C prerelease origin/prerelease

          git reset --hard origin/prerelease

          Write-Host "TEST updated!"

      # RUN TEST PROGRAM
      - name: Run TEST program
        shell: powershell
        run: |
          cd "C:\Users\miks1\Documents\STUNDAS DARBS\TEST\stundas_darbs"

          python hello_world.py

      # UPDATE MAIN FOLDER FROM MAIN BRANCH
      - name: Update MAIN folder
        shell: powershell
        run: |
          cd "C:\Users\miks1\Documents